/*
 - Copyright 1999-2016 Shanghai XiangTu Network Technology Co. Limit
*/
/*
 - Copyright 1999-2016 Shanghai XiangTu Network Technology Co. Limit
*/
package com.qc.pojo.goods;

import com.esotericsoftware.kryo.DefaultSerializer;
import com.esotericsoftware.kryo.serializers.CompatibleFieldSerializer;
import java.io.Serializable;

/**
* Category设置Kryo的CompatibleFieldSerializer
* Auto generated by Stanley Li
*/
@DefaultSerializer(CompatibleFieldSerializer.class)
public class Category implements Serializable {
    /**
     * 分类ID
     * tb_category.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * 分类名称
     * tb_category.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * 商品数量
     * tb_category.goods_num
     *
     * @mbggenerated
     */
    private Integer goodsNum;

    /**
     * 是否显示
     * tb_category.is_show
     *
     * @mbggenerated
     */
    private String isShow;

    /**
     * 是否导航
     * tb_category.is_menu
     *
     * @mbggenerated
     */
    private String isMenu;

    /**
     * 排序
     * tb_category.seq
     *
     * @mbggenerated
     */
    private Integer seq;

    /**
     * 上级ID
     * tb_category.parent_id
     *
     * @mbggenerated
     */
    private Integer parentId;

    /**
     * 模板ID
     * tb_category.template_id
     *
     * @mbggenerated
     */
    private Integer templateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_category
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 分类ID
     * This method returns the value of the database column tb_category.id
     *
     * @return the value of tb_category.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * 分类ID
     * This method sets the value of the database column tb_category.id
     *
     * @param id the value for tb_category.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 分类名称
     * This method returns the value of the database column tb_category.name
     *
     * @return the value of tb_category.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * 分类名称
     * This method sets the value of the database column tb_category.name
     *
     * @param name the value for tb_category.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * 商品数量
     * This method returns the value of the database column tb_category.goods_num
     *
     * @return the value of tb_category.goods_num
     *
     * @mbggenerated
     */
    public Integer getGoodsNum() {
        return goodsNum;
    }

    /**
     * 商品数量
     * This method sets the value of the database column tb_category.goods_num
     *
     * @param goodsNum the value for tb_category.goods_num
     *
     * @mbggenerated
     */
    public void setGoodsNum(Integer goodsNum) {
        this.goodsNum = goodsNum;
    }

    /**
     * 是否显示
     * This method returns the value of the database column tb_category.is_show
     *
     * @return the value of tb_category.is_show
     *
     * @mbggenerated
     */
    public String getIsShow() {
        return isShow;
    }

    /**
     * 是否显示
     * This method sets the value of the database column tb_category.is_show
     *
     * @param isShow the value for tb_category.is_show
     *
     * @mbggenerated
     */
    public void setIsShow(String isShow) {
        this.isShow = isShow;
    }

    /**
     * 是否导航
     * This method returns the value of the database column tb_category.is_menu
     *
     * @return the value of tb_category.is_menu
     *
     * @mbggenerated
     */
    public String getIsMenu() {
        return isMenu;
    }

    /**
     * 是否导航
     * This method sets the value of the database column tb_category.is_menu
     *
     * @param isMenu the value for tb_category.is_menu
     *
     * @mbggenerated
     */
    public void setIsMenu(String isMenu) {
        this.isMenu = isMenu;
    }

    /**
     * 排序
     * This method returns the value of the database column tb_category.seq
     *
     * @return the value of tb_category.seq
     *
     * @mbggenerated
     */
    public Integer getSeq() {
        return seq;
    }

    /**
     * 排序
     * This method sets the value of the database column tb_category.seq
     *
     * @param seq the value for tb_category.seq
     *
     * @mbggenerated
     */
    public void setSeq(Integer seq) {
        this.seq = seq;
    }

    /**
     * 上级ID
     * This method returns the value of the database column tb_category.parent_id
     *
     * @return the value of tb_category.parent_id
     *
     * @mbggenerated
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * 上级ID
     * This method sets the value of the database column tb_category.parent_id
     *
     * @param parentId the value for tb_category.parent_id
     *
     * @mbggenerated
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * 模板ID
     * This method returns the value of the database column tb_category.template_id
     *
     * @return the value of tb_category.template_id
     *
     * @mbggenerated
     */
    public Integer getTemplateId() {
        return templateId;
    }

    /**
     * 模板ID
     * This method sets the value of the database column tb_category.template_id
     *
     * @param templateId the value for tb_category.template_id
     *
     * @mbggenerated
     */
    public void setTemplateId(Integer templateId) {
        this.templateId = templateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_category
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Category other = (Category) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getGoodsNum() == null ? other.getGoodsNum() == null : this.getGoodsNum().equals(other.getGoodsNum()))
            && (this.getIsShow() == null ? other.getIsShow() == null : this.getIsShow().equals(other.getIsShow()))
            && (this.getIsMenu() == null ? other.getIsMenu() == null : this.getIsMenu().equals(other.getIsMenu()))
            && (this.getSeq() == null ? other.getSeq() == null : this.getSeq().equals(other.getSeq()))
            && (this.getParentId() == null ? other.getParentId() == null : this.getParentId().equals(other.getParentId()))
            && (this.getTemplateId() == null ? other.getTemplateId() == null : this.getTemplateId().equals(other.getTemplateId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_category
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getGoodsNum() == null) ? 0 : getGoodsNum().hashCode());
        result = prime * result + ((getIsShow() == null) ? 0 : getIsShow().hashCode());
        result = prime * result + ((getIsMenu() == null) ? 0 : getIsMenu().hashCode());
        result = prime * result + ((getSeq() == null) ? 0 : getSeq().hashCode());
        result = prime * result + ((getParentId() == null) ? 0 : getParentId().hashCode());
        result = prime * result + ((getTemplateId() == null) ? 0 : getTemplateId().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_category
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", goodsNum=").append(goodsNum);
        sb.append(", isShow=").append(isShow);
        sb.append(", isMenu=").append(isMenu);
        sb.append(", seq=").append(seq);
        sb.append(", parentId=").append(parentId);
        sb.append(", templateId=").append(templateId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}