/*
 - Copyright 1999-2016 Shanghai XiangTu Network Technology Co. Limit
*/
/*
 - Copyright 1999-2016 Shanghai XiangTu Network Technology Co. Limit
*/
package com.qc.pojo.goods;

import com.esotericsoftware.kryo.DefaultSerializer;
import com.esotericsoftware.kryo.serializers.CompatibleFieldSerializer;
import java.io.Serializable;

/**
* Para设置Kryo的CompatibleFieldSerializer
* Auto generated by Stanley Li
*/
@DefaultSerializer(CompatibleFieldSerializer.class)
public class Para implements Serializable {
    /**
     * id
     * tb_para.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * 名称
     * tb_para.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * 选项
     * tb_para.options
     *
     * @mbggenerated
     */
    private String options;

    /**
     * 排序
     * tb_para.seq
     *
     * @mbggenerated
     */
    private Integer seq;

    /**
     * 模板ID
     * tb_para.template_id
     *
     * @mbggenerated
     */
    private Integer templateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_para
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * id
     * This method returns the value of the database column tb_para.id
     *
     * @return the value of tb_para.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * id
     * This method sets the value of the database column tb_para.id
     *
     * @param id the value for tb_para.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 名称
     * This method returns the value of the database column tb_para.name
     *
     * @return the value of tb_para.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * 名称
     * This method sets the value of the database column tb_para.name
     *
     * @param name the value for tb_para.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * 选项
     * This method returns the value of the database column tb_para.options
     *
     * @return the value of tb_para.options
     *
     * @mbggenerated
     */
    public String getOptions() {
        return options;
    }

    /**
     * 选项
     * This method sets the value of the database column tb_para.options
     *
     * @param options the value for tb_para.options
     *
     * @mbggenerated
     */
    public void setOptions(String options) {
        this.options = options;
    }

    /**
     * 排序
     * This method returns the value of the database column tb_para.seq
     *
     * @return the value of tb_para.seq
     *
     * @mbggenerated
     */
    public Integer getSeq() {
        return seq;
    }

    /**
     * 排序
     * This method sets the value of the database column tb_para.seq
     *
     * @param seq the value for tb_para.seq
     *
     * @mbggenerated
     */
    public void setSeq(Integer seq) {
        this.seq = seq;
    }

    /**
     * 模板ID
     * This method returns the value of the database column tb_para.template_id
     *
     * @return the value of tb_para.template_id
     *
     * @mbggenerated
     */
    public Integer getTemplateId() {
        return templateId;
    }

    /**
     * 模板ID
     * This method sets the value of the database column tb_para.template_id
     *
     * @param templateId the value for tb_para.template_id
     *
     * @mbggenerated
     */
    public void setTemplateId(Integer templateId) {
        this.templateId = templateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_para
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Para other = (Para) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getOptions() == null ? other.getOptions() == null : this.getOptions().equals(other.getOptions()))
            && (this.getSeq() == null ? other.getSeq() == null : this.getSeq().equals(other.getSeq()))
            && (this.getTemplateId() == null ? other.getTemplateId() == null : this.getTemplateId().equals(other.getTemplateId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_para
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getOptions() == null) ? 0 : getOptions().hashCode());
        result = prime * result + ((getSeq() == null) ? 0 : getSeq().hashCode());
        result = prime * result + ((getTemplateId() == null) ? 0 : getTemplateId().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_para
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", options=").append(options);
        sb.append(", seq=").append(seq);
        sb.append(", templateId=").append(templateId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}