/*
 - Copyright 1999-2016 Shanghai XiangTu Network Technology Co. Limit
*/
/*
 - Copyright 1999-2016 Shanghai XiangTu Network Technology Co. Limit
*/
package com.qc.pojo.goods;

import com.esotericsoftware.kryo.DefaultSerializer;
import com.esotericsoftware.kryo.serializers.CompatibleFieldSerializer;
import java.io.Serializable;

/**
* Template设置Kryo的CompatibleFieldSerializer
* Auto generated by Stanley Li
*/
@DefaultSerializer(CompatibleFieldSerializer.class)
public class Template implements Serializable {
    /**
     * ID
     * tb_template.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * 模板名称
     * tb_template.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * 规格数量
     * tb_template.spec_num
     *
     * @mbggenerated
     */
    private Integer specNum;

    /**
     * 参数数量
     * tb_template.para_num
     *
     * @mbggenerated
     */
    private Integer paraNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_template
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * ID
     * This method returns the value of the database column tb_template.id
     *
     * @return the value of tb_template.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * ID
     * This method sets the value of the database column tb_template.id
     *
     * @param id the value for tb_template.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 模板名称
     * This method returns the value of the database column tb_template.name
     *
     * @return the value of tb_template.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * 模板名称
     * This method sets the value of the database column tb_template.name
     *
     * @param name the value for tb_template.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * 规格数量
     * This method returns the value of the database column tb_template.spec_num
     *
     * @return the value of tb_template.spec_num
     *
     * @mbggenerated
     */
    public Integer getSpecNum() {
        return specNum;
    }

    /**
     * 规格数量
     * This method sets the value of the database column tb_template.spec_num
     *
     * @param specNum the value for tb_template.spec_num
     *
     * @mbggenerated
     */
    public void setSpecNum(Integer specNum) {
        this.specNum = specNum;
    }

    /**
     * 参数数量
     * This method returns the value of the database column tb_template.para_num
     *
     * @return the value of tb_template.para_num
     *
     * @mbggenerated
     */
    public Integer getParaNum() {
        return paraNum;
    }

    /**
     * 参数数量
     * This method sets the value of the database column tb_template.para_num
     *
     * @param paraNum the value for tb_template.para_num
     *
     * @mbggenerated
     */
    public void setParaNum(Integer paraNum) {
        this.paraNum = paraNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_template
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Template other = (Template) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getSpecNum() == null ? other.getSpecNum() == null : this.getSpecNum().equals(other.getSpecNum()))
            && (this.getParaNum() == null ? other.getParaNum() == null : this.getParaNum().equals(other.getParaNum()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_template
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getSpecNum() == null) ? 0 : getSpecNum().hashCode());
        result = prime * result + ((getParaNum() == null) ? 0 : getParaNum().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_template
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", specNum=").append(specNum);
        sb.append(", paraNum=").append(paraNum);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}