/*
 - Copyright 1999-2016 Shanghai XiangTu Network Technology Co. Limit
*/
package com.qc.dao.goods;

import com.qc.example.goods.ParaExample;
import com.qc.pojo.goods.Para;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ParaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_para
     *
     * @mbggenerated
     */
    int countByExample(ParaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_para
     *
     * @mbggenerated
     */
    int deleteByExample(ParaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_para
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_para
     *
     * @mbggenerated
     */
    int insert(Para record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_para
     *
     * @mbggenerated
     */
    int insertSelective(Para record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_para
     *
     * @mbggenerated
     */
    List<Para> selectByExample(ParaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_para
     *
     * @mbggenerated
     */
    Para selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_para
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Para record, @Param("example") ParaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_para
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Para record, @Param("example") ParaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_para
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Para record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_para
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Para record);
}