/*
 - Copyright 1999-2016 Shanghai XiangTu Network Technology Co. Limit
*/
package com.qc.dao.goods;

import com.qc.example.goods.SpecExample;
import com.qc.pojo.goods.Spec;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SpecMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_spec
     *
     * @mbggenerated
     */
    int countByExample(SpecExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_spec
     *
     * @mbggenerated
     */
    int deleteByExample(SpecExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_spec
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_spec
     *
     * @mbggenerated
     */
    int insert(Spec record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_spec
     *
     * @mbggenerated
     */
    int insertSelective(Spec record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_spec
     *
     * @mbggenerated
     */
    List<Spec> selectByExample(SpecExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_spec
     *
     * @mbggenerated
     */
    Spec selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_spec
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Spec record, @Param("example") SpecExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_spec
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Spec record, @Param("example") SpecExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_spec
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Spec record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_spec
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Spec record);
}